SELECT PUBLIC.INVOICE.CUSTOMERID, PUBLIC.CUSTOMER.FIRSTNAME, PUBLIC.CUSTOMER.LASTNAME,
  PUBLIC.INVOICE.TOTAL
  FROM
       PUBLIC.INVOICE JOIN PUBLIC.CUSTOMER ON PUBLIC.INVOICE.CUSTOMERID = PUBLIC.CUSTOMER.ID
